image: centos:7

before_script:
- yum -y install epel-release
- yum -y install make gcc gcc-c++ autoconf
- yum -y install cmake
- yum -y install json-devel

build-bare:
 script:
  - echo "Hello World"
  - mkdir build
  - cd build
  - cmake ..
  - make

build:
 script:
  - echo "Hello World"
  - curl -o /etc/yum.repos.d/picoscope.repo https://labs.picotech.com/rpm/picoscope.repo
  - rpmkeys --import https://labs.picotech.com/rpm/repodata/repomd.xml.key  
  - yum -y install libftdi-devel libftdi-c++-devel
  - yum -y install opencv-devel
  - yum -y install picoscope
  - yum -y install autoconf automake git swig
  - pushd $(mktemp -d)
  - git clone https://github.com/l29ah/libmpsse.git
  - cd libmpsse/src
  - git checkout -b v1.3.2  v1.3.2
  - autoreconf
  - ./configure CFLAGS="-std=c99" --disable-python
  - make
  - make install
  - popd  
  - mkdir build
  - cd build
  - cmake ..
  - make
